"""tools/retriever_tools.py

LangChain @tool that wraps the full hybrid-RAG retrieval pipeline.

The Remediator LLM calls `retrieve_schema_context` directly with:
  - retrieval_queries : targeted Resource.Property strings for ChromaDB
    semantic search, generated by the LLM from the annotated template
    and validation errors.
  - seed_resources    : list of AWS CloudFormation resource type strings
    (e.g. ["AWS::S3::Bucket", "AWS::IAM::Role"]) for Neo4j graph
    traversal. The LLM extracts these from the error context; the full
    template YAML is NOT passed - it is already visible in the prompt.

Design constraints:
  - No imports from agents/  (unidirectional: tools <- agents).
  - All heavy I/O (DB connections) is deferred to call-time.
  - Intentionally stateless: all context passed as arguments.
"""
from __future__ import annotations

from typing import Annotated

from langchain_core.tools import tool
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Input schema
# ---------------------------------------------------------------------------

class RetrieveSchemaContextInput(BaseModel):
    """Input schema for retrieve_schema_context."""

    retrieval_queries: Annotated[
        list[str],
        Field(
            description=(
                "Targeted AWS CloudFormation schema-lookup queries you generated "
                "based on the annotated template and validation errors. "
                "Each query should name a specific Resource.Property pair "
                "(e.g. 'AWS::S3::Bucket.BucketEncryption') or describe a "
                "schema constraint you need to look up. "
                "Do NOT include queries already used in previous iterations."
            )
        ),
    ]
    seed_resources: Annotated[
        list[str],
        Field(
            description=(
                "AWS CloudFormation resource type strings extracted from the "
                "template that are related to the current errors. Used to seed "
                "the Neo4j graph traversal so related schema blocks are fetched "
                "even when the vector search misses them. "
                "Example: ['AWS::S3::Bucket', 'AWS::IAM::Role', 'AWS::KMS::Key']. "
                "Only include resource types relevant to the current errors, "
                "not every resource in the template."
            )
        ),
    ]


# ---------------------------------------------------------------------------
# Tool
# ---------------------------------------------------------------------------

@tool(args_schema=RetrieveSchemaContextInput)
def retrieve_schema_context(
    retrieval_queries: list[str],
    seed_resources: list[str],
) -> str:
    """Retrieve official AWS CloudFormation schema context for the current template errors.

    Runs a two-stage hybrid retrieval pipeline:
      Stage 1 - ChromaDB semantic search over pre-indexed CFN property chunks,
                driven by your retrieval_queries.
      Stage 2 - Neo4j graph traversal seeded by seed_resources, fetching related
                schema blocks even when vector search misses them.

    Call this tool when cfn-lint or deployment errors are present and you need
    the official schema (required properties, types, constraints) to fix them.

    Pass:
      retrieval_queries : Resource.Property queries YOU generated from the errors.
      seed_resources    : AWS resource types related to the errors (e.g.
                          ['AWS::S3::Bucket', 'AWS::IAM::Role']). Extract these
                          from the annotated template - do NOT copy the full YAML.

    Do NOT call this tool for YAML syntax errors or pure security violations
    (checkov / trivy IDs) - those do not benefit from schema context.

    Returns a multi-section schema context string to use in your fix objectives.
    """
    # Deferred imports - keep module-level import cost negligible.
    from tools.cfn_hybrid_rag import execute_hybrid_retrieval  # noqa: PLC0415

    print(
        f"[Tool:retrieve_schema_context] Running hybrid retrieval with "
        f"{len(retrieval_queries)} queries and {len(seed_resources)} seed resources..."
    )

    # execute_hybrid_retrieval expects set[str] for seed_resources and uses the
    # `|` set-union operator internally. Pydantic/LangChain JSON schema does not
    # support Python sets, so the tool input is list[str]; we cast at the call site.
    context = execute_hybrid_retrieval(
        retrieval_queries=retrieval_queries,
        seed_resources=set(seed_resources),
    )

    print(f"[Tool:retrieve_schema_context] Context: {len(context)} chars returned.")
    return context
